stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t bhramar/gitlab-ci-android:latest .

push_latest:
  stage: push
  only:
    - master
  script:
    - docker tag bhramar/gitlab-ci-android:latest bhramar/gitlab-ci-android:latest
    - docker push bhramar/gitlab-ci-android:latest
